### ISSUE TITLE
Issue building...

### ISSUE THREAD

**Issue by gcasa** [gnustep/tools-android#22] opened 2024-08-09 03:59 UTC
I have installed the latest Android Studio and NDK.  I am getting the following failure... I believe it didn't properly patch libffi...

```
### Building
MAKE i386-apple-darwin23.5.0 :        0 * all-all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in include
make[3]: Nothing to be done for `all'.
Making all in testsuite
make[3]: Nothing to be done for `all'.
Making all in man
make[3]: Nothing to be done for `all'.
depbase=`echo src/arm/ffi.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/arm/ffi.lo -MD -MP -MF $depbase.Tpo -c -o src/arm/ffi.lo ../src/arm/ffi.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/arm/sysv.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src  -I. -I../include -Iinclude -I../src -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -MT src/arm/sysv.lo -MD -MP -MF $depbase.Tpo -c -o src/arm/sysv.lo ../src/arm/sysv.S &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/arm/ffi.lo -MD -MP -MF src/arm/.deps/ffi.Tpo -c ../src/arm/ffi.c -o src/arm/ffi.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -I. -I../include -Iinclude -I../src -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -MT src/arm/sysv.lo -MD -MP -MF src/arm/.deps/sysv.Tpo -c ../src/arm/sysv.S -o src/arm/sysv.o
depbase=`echo src/prep_cif.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/prep_cif.lo -MD -MP -MF $depbase.Tpo -c -o src/prep_cif.lo ../src/prep_cif.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/types.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/types.lo -MD -MP -MF $depbase.Tpo -c -o src/types.lo ../src/types.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/raw_api.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/raw_api.lo -MD -MP -MF $depbase.Tpo -c -o src/raw_api.lo ../src/raw_api.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/java_raw_api.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/java_raw_api.lo -MD -MP -MF $depbase.Tpo -c -o src/java_raw_api.lo ../src/java_raw_api.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/closures.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/closures.lo -MD -MP -MF $depbase.Tpo -c -o src/closures.lo ../src/closures.c &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/tramp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/tramp.lo -MD -MP -MF $depbase.Tpo -c -o src/tramp.lo ../src/tramp.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c -o src/closures.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c -o src/java_raw_api.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/types.lo -MD -MP -MF src/.deps/types.Tpo -c ../src/types.c -o src/types.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/raw_api.lo -MD -MP -MF src/.deps/raw_api.Tpo -c ../src/raw_api.c -o src/raw_api.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/prep_cif.lo -MD -MP -MF src/.deps/prep_cif.Tpo -c ../src/prep_cif.c -o src/prep_cif.o
libtool: compile:  /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -MT src/tramp.lo -MD -MP -MF src/.deps/tramp.Tpo -c ../src/tramp.c -o src/tramp.o
../src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  328 |   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
      |                                              ^
include/ffi.h:315:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
  315 | size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
      |                                                        ^
../src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  331 |   ffi_java_ptrarray_to_raw (cif, avalue, raw);
      |   ^
include/ffi.h:311:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
  311 | void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
      |                                                                                             ^
In file included from ../src/closures.c:572:
../src/dlmalloc.c:3390:7: warning: variable 'nfences' set but not used [-Wunused-but-set-variable]
 3390 |   int nfences = 0;
      |       ^
2 warnings generated.
1 warning generated.
/bin/sh ./libtool  --tag=CC   --mode=link /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang  -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions  -L/Users/heron/Library/Android/GNUstep/armeabi-v7a/lib -fuse-ld=lld -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--gc-sections -Wl,--exclude-libs,libunwind.a -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo src/tramp.lo   src/arm/ffi.lo src/arm/sysv.lo -lc++_shared
/bin/sh ./libtool  --tag=CC   --mode=link /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi24-clang  -Wall -g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -mthumb -fexceptions -no-undefined -version-info `grep -v '^#' ../libtool-version`   '-L/Users/heron/Library/Android/GNUstep/armeabi-v7a/lib' -Xcompiler '-fuse-ld=lld' '-Wl,--build-id=sha1' '-Wl,--no-rosegment' '-Wl,--gc-sections' '-Wl,--exclude-libs,libunwind.a'  -L/Users/heron/Library/Android/GNUstep/armeabi-v7a/lib -fuse-ld=lld -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--gc-sections -Wl,--exclude-libs,libunwind.a -o libffi.la -rpath /Users/heron/Library/Android/GNUstep/armeabi-v7a/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo src/tramp.lo  src/arm/ffi.lo src/arm/sysv.lo -lc++_shared
libtool: link: /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar cr .libs/libffi_convenience.a  src/prep_cif.o src/types.o src/raw_api.o src/java_raw_api.o src/closures.o src/tramp.o src/arm/ffi.o src/arm/sysv.o
libtool: link: /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar cr .libs/libffi.a  src/prep_cif.o src/types.o src/raw_api.o src/java_raw_api.o src/closures.o src/tramp.o src/arm/ffi.o src/arm/sysv.o
libtool: link: /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib .libs/libffi_convenience.a
libtool: link: /Users/heron/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib .libs/libffi.a
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
libtool: link: ( cd ".libs" && rm -f "libffi.la" && ln -s "../libffi.la" "libffi.la" )
MAKE i386-apple-darwin23.5.0 :        0 * all-configured
make[1]: *** No rule to make target `all-configured'.  Stop.
make: *** [all-configured] Error 2

### phases/13-libffi.sh failed for ABI armeabi-v7a
```

**Comment by triplef** [comment] 2024-08-09 06:31
Looks like a duplicate of #20.

**Closed by triplef** 2024-08-09 06:31 UTC
